/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Knjiga;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author andri
 */
public class DodajStavkuIznajmljivanjaForma extends javax.swing.JFrame {
    
    /**
     * Creates new form DodajStavkuIznajmljivanjaForma
     */
    public DodajStavkuIznajmljivanjaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOpisStakve = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBrojDana = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIznosPoDanu = new javax.swing.JTextField();
        txtUkupanIznosStavke = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        cmbKnjige = new javax.swing.JComboBox<>();
        lblIdIznajmljivanje = new javax.swing.JLabel();
        txtIdIznajmljivanja = new javax.swing.JTextField();
        btnAzuriraj = new javax.swing.JButton();
        txtDatumOd = new javax.swing.JTextField();
        txtDatumDo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtOpisStakve.setText("a");

        jLabel3.setText("Opis Stavke");

        jLabel4.setText("Datum od(yyyy-MM-dd)");

        jLabel5.setText("Datum do(yyyy-MM-dd)");

        txtBrojDana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrojDanaActionPerformed(evt);
            }
        });

        jLabel6.setText("Broj Dana");

        jLabel7.setText("Ukupan iznos stavke");

        jLabel8.setText("Iznos po danu");

        jLabel9.setText("Knjiga");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        cmbKnjige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKnjigeActionPerformed(evt);
            }
        });

        lblIdIznajmljivanje.setText("Id Iznajmljivanje");

        txtIdIznajmljivanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdIznajmljivanjaActionPerformed(evt);
            }
        });

        btnAzuriraj.setText("Azuriraj");

        txtDatumOd.setText("2023-10-11");

        txtDatumDo.setText("2023-11-11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(lblIdIznajmljivanje)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOpisStakve)
                    .addComponent(txtBrojDana)
                    .addComponent(txtIznosPoDanu)
                    .addComponent(txtUkupanIznosStavke)
                    .addComponent(cmbKnjige, 0, 86, Short.MAX_VALUE)
                    .addComponent(txtIdIznajmljivanja)
                    .addComponent(txtDatumOd)
                    .addComponent(txtDatumDo))
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodaj)
                    .addComponent(btnAzuriraj))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnDodaj)
                        .addGap(33, 33, 33)
                        .addComponent(btnAzuriraj))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdIznajmljivanje)
                            .addComponent(txtIdIznajmljivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtOpisStakve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtBrojDana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtIznosPoDanu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtUkupanIznosStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cmbKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbKnjigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKnjigeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKnjigeActionPerformed

    private void txtBrojDanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrojDanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrojDanaActionPerformed

    private void txtIdIznajmljivanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdIznajmljivanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdIznajmljivanjaActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDodajActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzuriraj;
    private javax.swing.JButton btnDodaj;
    private javax.swing.JComboBox<Knjiga> cmbKnjige;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblIdIznajmljivanje;
    private javax.swing.JTextField txtBrojDana;
    private javax.swing.JTextField txtDatumDo;
    private javax.swing.JTextField txtDatumOd;
    private javax.swing.JTextField txtIdIznajmljivanja;
    private javax.swing.JTextField txtIznosPoDanu;
    private javax.swing.JTextField txtOpisStakve;
    private javax.swing.JTextField txtUkupanIznosStavke;
    // End of variables declaration//GEN-END:variables

    public JComboBox<Knjiga> getCmbKnjige() {
        return cmbKnjige;
    }

    public JButton getBtnDodaj() {
        return btnDodaj;
    }

    public void addBtnDodajActionListener(ActionListener actionListener) {
        btnDodaj.addActionListener(actionListener);
    }

    public JTextField getTxtIznosPoDanu() {
        return txtIznosPoDanu;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public JTextField getTxtBrojDana() {
        return txtBrojDana;
    }

    public JTextField getTxtDatumDo() {
        return txtDatumDo;
    }

    public void setTxtDatumDo(JTextField txtDatumDo) {
        this.txtDatumDo = txtDatumDo;
    }

    public JTextField getTxtDatumOd() {
        return txtDatumOd;
    }

    public void setTxtDatumOd(JTextField txtDatumOd) {
        this.txtDatumOd = txtDatumOd;
    }

   

    

    public JTextField getTxtOpisStakve() {
        return txtOpisStakve;
    }

    public JTextField getTxtUkupanIznosStavke() {
        return txtUkupanIznosStavke;
    }

    public JTextField getTxtIdIznajmljivanja() {
        return txtIdIznajmljivanja;
    }

    public void setTxtIdIznajmljivanja(JTextField txtIdIznajmljivanja) {
        this.txtIdIznajmljivanja = txtIdIznajmljivanja;
    }

    public JButton getBtnAzuriraj() {
        return btnAzuriraj;
    }

    public void setBtnAzuriraj(JButton btnAzuriraj) {
        this.btnAzuriraj = btnAzuriraj;
    }

    public JLabel getLblIdIznajmljivanje() {
        return lblIdIznajmljivanje;
    }

    public void setLblIdIznajmljivanje(JLabel lblIdIznajmljivanje) {
        this.lblIdIznajmljivanje = lblIdIznajmljivanje;
    }

    public void addBtnAzurirajActionListener(ActionListener actionListener) {
        btnAzuriraj.addActionListener(actionListener);
    }

    
    
    
    

    
    
}
