/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Citalac;
import domen.Radnik;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author andri
 */
public class DodajIznajmljivanjeForma extends javax.swing.JFrame {

    /**
     * Creates new form DodajIznajmljivanjeForma
     */
    public DodajIznajmljivanjeForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdIznajmljivanja = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUkupanIznos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOpisIznajmljivanja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbRadnici = new javax.swing.JComboBox<>();
        cmbCitaoci = new javax.swing.JComboBox<>();
        btnDodajStavkuIznajmljivanja = new javax.swing.JButton();
        btnKreirajIznajmljivanje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        txtIdIznajmljivanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdIznajmljivanjaActionPerformed(evt);
            }
        });

        jLabel2.setText("Ukupan Iznos");

        jLabel3.setText("Opis");

        jLabel4.setText("Radnik");

        jLabel5.setText("Citalac");

        btnDodajStavkuIznajmljivanja.setText("Dodaj Stavku Iznajmljivanja");
        btnDodajStavkuIznajmljivanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuIznajmljivanjaActionPerformed(evt);
            }
        });

        btnKreirajIznajmljivanje.setText("Kreiraj Iznajmljivanje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnKreirajIznajmljivanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDodajStavkuIznajmljivanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRadnici, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUkupanIznos)
                    .addComponent(txtOpisIznajmljivanja)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdIznajmljivanja, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cmbCitaoci, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdIznajmljivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOpisIznajmljivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbRadnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCitaoci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnDodajStavkuIznajmljivanja)
                .addGap(18, 18, 18)
                .addComponent(btnKreirajIznajmljivanje)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdIznajmljivanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdIznajmljivanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdIznajmljivanjaActionPerformed

    private void btnDodajStavkuIznajmljivanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuIznajmljivanjaActionPerformed
        
    }//GEN-LAST:event_btnDodajStavkuIznajmljivanjaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public JComboBox<Citalac> getCmbCitaoci() {
        return cmbCitaoci;
    }

    public void setCmbCitaoci(JComboBox<Citalac> cmbCitaoci) {
        this.cmbCitaoci = cmbCitaoci;
    }

    public JComboBox<Radnik> getCmbRadnici() {
        return cmbRadnici;
    }

    public void setCmbRadnici(JComboBox<Radnik> cmbRadnici) {
        this.cmbRadnici = cmbRadnici;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavkuIznajmljivanja;
    private javax.swing.JButton btnKreirajIznajmljivanje;
    private javax.swing.JComboBox<Citalac> cmbCitaoci;
    private javax.swing.JComboBox<Radnik> cmbRadnici;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtIdIznajmljivanja;
    private javax.swing.JTextField txtOpisIznajmljivanja;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    public void dodajStavkuIznajmljivanjaAddActionListener(ActionListener actionListener) {
         btnDodajStavkuIznajmljivanja.addActionListener(actionListener);
    }

    public JTextField getTxtIdIznajmljivanja() {
        return txtIdIznajmljivanja;
    }

    public JButton getBtnKreirajIznajmljivanje() {
        return btnKreirajIznajmljivanje;
    }

    public void kreirajIznajmljivanjeAddActionListener(ActionListener actionListener) {
        btnKreirajIznajmljivanje.addActionListener(actionListener);
    }

    public JTextField getTxtOpisIznajmljivanja() {
        return txtOpisIznajmljivanja;
    
        
    
    
    
}

    public JTextField getTxtUkupanIznos() {
        return txtUkupanIznos;
    }

    public void setTxtUkupanIznos(JTextField txtUkupanIznos) {
        this.txtUkupanIznos = txtUkupanIznos;
    }
    
    
}