/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Citalac;
import domen.Radnik;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author andri
 */
public class DodajIznajmljivanjeForma extends javax.swing.JFrame {

    /**
     * Creates new form DodajIznajmljivanjeForma
     */
    public DodajIznajmljivanjeForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel2 = new javax.swing.JLabel();
        txtUkupanIznos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOpisIznajmljivanja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbRadnici = new javax.swing.JComboBox<>();
        cmbCitaoci = new javax.swing.JComboBox<>();
        btnDodajStavkuIznajmljivanja = new javax.swing.JButton();
        btnKreirajIznajmljivanje = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnAzuriraj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeIznajmljivanja = new javax.swing.JTable();
        btnAzurirajStavku = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Ukupan Iznos");

        jLabel3.setText("Opis");

        jLabel4.setText("Radnik");

        jLabel5.setText("Citalac");

        btnDodajStavkuIznajmljivanja.setText("Dodaj Stavku Iznajmljivanja");
        btnDodajStavkuIznajmljivanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuIznajmljivanjaActionPerformed(evt);
            }
        });

        btnKreirajIznajmljivanje.setText("Kreiraj Iznajmljivanje");

        lblId.setText("Id ");

        btnAzuriraj.setText("Azuriraj Iznajmljivanje");

        tblStavkeIznajmljivanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkeIznajmljivanja);

        btnAzurirajStavku.setText("Izmeni Stavku");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(209, 209, 209)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbRadnici, 0, 1, Short.MAX_VALUE)
                                    .addComponent(txtUkupanIznos)
                                    .addComponent(txtOpisIznajmljivanja)
                                    .addComponent(cmbCitaoci, 0, 1, Short.MAX_VALUE)
                                    .addComponent(txtId)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnKreirajIznajmljivanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDodajStavkuIznajmljivanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(lblId))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnAzurirajStavku)
                .addGap(333, 333, 333)
                .addComponent(btnAzuriraj)
                .addGap(0, 235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblId)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOpisIznajmljivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbRadnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCitaoci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnDodajStavkuIznajmljivanja)
                .addGap(18, 18, 18)
                .addComponent(btnKreirajIznajmljivanje)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAzurirajStavku)
                    .addComponent(btnAzuriraj))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajStavkuIznajmljivanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuIznajmljivanjaActionPerformed

    }//GEN-LAST:event_btnDodajStavkuIznajmljivanjaActionPerformed

    /**
     * @param args the command line arguments
     */
    public JComboBox<Citalac> getCmbCitaoci() {
        return cmbCitaoci;
    }

    public void setCmbCitaoci(JComboBox<Citalac> cmbCitaoci) {
        this.cmbCitaoci = cmbCitaoci;
    }

    public JComboBox<Radnik> getCmbRadnici() {
        return cmbRadnici;
    }

    public void setCmbRadnici(JComboBox<Radnik> cmbRadnici) {
        this.cmbRadnici = cmbRadnici;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzuriraj;
    private javax.swing.JButton btnAzurirajStavku;
    private javax.swing.JButton btnDodajStavkuIznajmljivanja;
    private javax.swing.JButton btnKreirajIznajmljivanje;
    private javax.swing.JComboBox<Citalac> cmbCitaoci;
    private javax.swing.JComboBox<Radnik> cmbRadnici;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable tblStavkeIznajmljivanja;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtOpisIznajmljivanja;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    public void addBtnDodajStavkuIznajmljivanjaAddActionListener(ActionListener actionListener) {
        btnDodajStavkuIznajmljivanja.addActionListener(actionListener);
    }

    public void addBtnAzurirajActionListener(ActionListener actionListener) {
        btnAzuriraj.addActionListener(actionListener);
    }

    public JButton getBtnKreirajIznajmljivanje() {
        return btnKreirajIznajmljivanje;
    }

    public void addBtnKreirajIznajmljivanjeAddActionListener(ActionListener actionListener) {
        btnKreirajIznajmljivanje.addActionListener(actionListener);
    }

    public JTextField getTxtOpisIznajmljivanja() {
        return txtOpisIznajmljivanja;

    }

    public JTextField getTxtUkupanIznos() {
        return txtUkupanIznos;
    }

    public void setTxtUkupanIznos(JTextField txtUkupanIznos) {
        this.txtUkupanIznos = txtUkupanIznos;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JButton getBtnDodajStavkuIznajmljivanja() {
        return btnDodajStavkuIznajmljivanja;
    }

    public void setBtnDodajStavkuIznajmljivanja(JButton btnDodajStavkuIznajmljivanja) {
        this.btnDodajStavkuIznajmljivanja = btnDodajStavkuIznajmljivanja;
    }

    public JButton getBtnAzuriraj() {
        return btnAzuriraj;
    }

    public void setBtnAzuriraj(JButton btnAzuriraj) {
        this.btnAzuriraj = btnAzuriraj;
    }

    public JLabel getLblId() {
        return lblId;
    }

    public void setLblId(JLabel lblId) {
        this.lblId = lblId;
    }

    public JTable getTblStavkeIznajmljivanja() {
        return tblStavkeIznajmljivanja;
    }

    public void setTblStavkeIznajmljivanja(JTable tblStavkeIznajmljivanja) {
        this.tblStavkeIznajmljivanja = tblStavkeIznajmljivanja;
    }

    public JButton getBtnAzurirajStavku() {
        return btnAzurirajStavku;
    }

    public void setBtnAzurirajStavku(JButton btnAzurirajStavku) {
        this.btnAzurirajStavku = btnAzurirajStavku;
    }

    public void addBtnAzurirajStavkuIznajmljivanjaActionListener(ActionListener al) {
        btnAzurirajStavku.addActionListener(al);
    }

}
